apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  annotations:
    lbipam.cilium.io/ips: "172.18.50.1"
spec:
  gatewayClassName: cilium
  listeners:
  - name: web-gw
    port: 80
    protocol: HTTP
  - name: https-gw
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: gateway-tls-secret
          kind: Secret
