version: '3'

vars:
  GWAPI_VIP: 172.18.50.1
  INGRESS_VIP: 172.18.50.2
  GWAPI_HOSTNAME:
    sh: echo "podinfo.{{.GWAPI_VIP}}.nip.io"
  INGRESS_HOSTNAME:
    sh: echo "podinfo.{{.INGRESS_VIP}}.nip.io"
  HUBBLE_HOSTNAME:
    sh: echo "hubble.{{.INGRESS_VIP}}.nip.io"

tasks:
  default:
    cmds:
      - task --list-all
  update-vips:
    cmds:
      - yq -i e '.httpRoute.hostnames[0] = "{{.GWAPI_HOSTNAME}}"' app/podinfo-gwapi.yaml
      - yq -i e '.ingress.hosts[0].host = "{{.INGRESS_HOSTNAME}}"' app/podinfo-ingress.yaml
      - yq -i e '.spec.blocks[0].cidr = "{{.GWAPI_VIP}}/32"' cilium/pool.yaml
      - yq -i e '.spec.blocks[1].cidr = "{{.INGRESS_VIP}}/32"' cilium/pool.yaml
      - yq -i e '.metadata.annotations["lbipam.cilium.io/ips"] = "{{.GWAPI_VIP}}"' cilium/gateway.yaml
  kind:
    cmds:
      - kind create cluster --config=./cluster.yaml
  delete:
    cmds:
      - kind delete cluster
  gwapi:
    vars:
      version: v1.4.1
    cmds:
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{.version}}/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{.version}}/config/crd/standard/gateway.networking.k8s.io_gateways.yaml
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{.version}}/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{.version}}/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{.version}}/config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{.version}}/config/crd/standard/gateway.networking.k8s.io_backendtlspolicies.yaml
      - kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{.version}}/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  cilium:
    cmds:
      - |
        cilium install \
          --set kubeProxyReplacement=true \
          --set gatewayAPI.enabled=true \
          --set ingressController.enabled=true \
          --set ingressController.default=true \
          --set ingressController.loadbalancerMode=shared \
          --set ingressController.service.loadBalancerIP={{.INGRESS_VIP}} \
          --set l2announcements.enabled=true \
          --set hubble.enabled=true \
          --set hubble.relay.enabled=true \
          --set hubble.ui.enabled=true \
          --set hubble.ui.ingress.enabled=true \
          --set hubble.ui.ingress.className=cilium \
          --set "hubble.ui.ingress.hosts={{{.HUBBLE_HOSTNAME}}}"
      - cilium status --wait
      - cilium hubble enable --ui
  lb:
    cmds:
      - kubectl apply -f cilium
  podinfo-gwapi:
    cmds:
      - helm upgrade --install podinfo-gwapi oci://ghcr.io/stefanprodan/charts/podinfo -f app/podinfo-gwapi.yaml
  podinfo-ingress:
    cmds:
      - helm upgrade --install podinfo-ingress oci://ghcr.io/stefanprodan/charts/podinfo -f app/podinfo-ingress.yaml
  test-gwapi:
    cmds:
      - while /bin/true; do curl -s {{.GWAPI_HOSTNAME}} | jq -r .hostname;sleep 1;done
  test-ingress:
    cmds:
      - while /bin/true; do curl -s {{.INGRESS_HOSTNAME}} | jq -r .hostname;sleep 1;done
  install:
    cmds:
      - task: kind
      - task: gwapi
      - task: cilium
      - task: lb
      - task: podinfo-gwapi
      - task: podinfo-ingress
