replicaCount: 2
logLevel: info
ui:
  color: "#e8563a"
  message: "served via Ingress"

podAnnotations:
  policy.cilium.io/proxy-visibility: "<Ingress/80/TCP/HTTP>,<Egress/80/TCP/HTTP>"

ingress:
  enabled: true
  className: cilium
  hosts:
    - host: podinfo.172.18.50.2.nip.io
      paths:
        - path: /
          pathType: Prefix
